import './globals.css'
import type { Metadata } from 'next'
import { Kanit } from 'next/font/google'

const kanit = Kanit({
  weight: ['200', '300', '400', '500', '600', '700'],
  style: ['normal'],
  variable: '--font-noto_sans_thai',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Anonymous-Message ❤️😉',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <div className="bg-[#080c11] min-h-screen">
          <div className="container mx-auto px-20 pt-14">
            {children}
          </div>
        </div>

        <script src="https://kit.fontawesome.com/a59b4d3f29.js" />
      </body>
    </html>
  )
}
